// This file has been autogenerated from a class added in the UI designer.

using System;
using System.IO;
using Foundation;
using UIKit;

namespace StoreDataIOS
{
	public partial class ListController : UITableViewController
	{
		public ListController (IntPtr handle) : base (handle)
		{
		}


        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            ///retrieve the information from the file 
            var documents = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
            var filename = Path.Combine(documents, "MyContacts.txt");
            var text = File.ReadAllText(filename);

            string[] line = text.Split(',');

            Contacts mycontact = new Contacts(line[0], line[1]);

            //create an array of items (type contact ) that will go in the table 

            Contacts[] contactsList = { mycontact };

            /// add your array as source to the table
            contactTable.Source = new TableSource(contactsList, this);





        }

    }
}
