// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.IO;
using Foundation;
using UIKit;

namespace StoreDataIOS
{
	public partial class ListController : UITableViewController
	{
		public ListController (IntPtr handle) : base (handle)
		{
		}


        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            ///retrieve the information from the file 
            var documents = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
            var filename = Path.Combine(documents, "MyContacts.txt");
            var text = File.ReadAllText(filename);
            Contacts mycontact;
            List<Contacts> listContactsList = new List<Contacts>();
            int counter = 0;
            string[] line = text.Split(',');
            for (int i = 0; i < line.Length / 2;i++)
            {
                mycontact = new Contacts(line[counter+i], line[counter+i+1]);
                counter++;
                listContactsList.Add(mycontact);
            }
            //create an array of items (type contact ) that will go in the table 
            Contacts[] contactsList= listContactsList.ToArray();
            /// add your array as source to the table
            contactTable.Source = new TableSource(contactsList, this);





        }

    }
}
