// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace StoreDataIOS
{
	public partial class nameBox : UITextField
	{
		public nameBox (IntPtr handle) : base (handle)
		{
		}
	}
}
